# Generated by Django 5.2.17 on 2026-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('group', models.CharField(choices=[('buyer', 'Покупателю'), ('partner', 'Компаниям'), ('hidden', 'Не показывать в подвале')], db_index=True, default='buyer', max_length=16, verbose_name='колонка в подвале')),
                ('lead', models.CharField(blank=True, help_text='Одна строка под заголовком. Необязательно.', max_length=300, verbose_name='подзаголовок')),
                ('lead_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии покажется русский.', max_length=300, verbose_name='подзаголовок по-украински')),
                ('body', models.TextField(help_text='Обычный текст. Пустая строка разделяет абзацы, строка, начинающаяся с «— », становится пунктом списка, строка вида «## Заголовок» — подзаголовком.', verbose_name='текст')),
                ('body_uk', models.TextField(blank=True, help_text='Разметка та же. Если не заполнить, на украинской версии покажется русский текст.', verbose_name='текст по-украински')),
                ('external_url', models.CharField(blank=True, help_text='Если заполнить, пункт в подвале ведёт сюда, а не на страницу с текстом. Например, /price/xlsx/', max_length=300, verbose_name='внешняя ссылка')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы сайта',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
    ]
