# Generated by Django 5.2.17 on 2026-09-16 18:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('code', models.CharField(help_text='Служебный, менять не нужно: по нему группа связана со справочником.', max_length=32, unique=True, verbose_name='ключ')),
                ('name', models.CharField(max_length=80, verbose_name='подпись в панели')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, останется русская подпись.', max_length=80, verbose_name='подпись по-украински')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галку — группа пропадёт из панели слева, но останется в карточке товара.', verbose_name='показывать в подборе')),
                ('has_search', models.BooleanField(default=False, help_text='Нужно, когда значений много.', verbose_name='поле поиска внутри группы')),
            ],
            options={
                'verbose_name': 'группа подбора',
                'verbose_name_plural': 'панель подбора',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'цветок',
                'verbose_name_plural': 'цветы',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'типы товаров',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'повод',
                'verbose_name_plural': 'поводы',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('color', models.CharField(default='#4A6B45', help_text='HEX, например #4A6B45. Этим цветом красится плашка на карточке.', max_length=7, verbose_name='цвет плашки')),
                ('is_orderable', models.BooleanField(default=True, help_text='Снимите галку для статусов вроде «Снят с продажи».', verbose_name='можно добавить в корзину')),
                ('note', models.CharField(blank=True, help_text='Показывается мелким шрифтом рядом со статусом.', max_length=120, verbose_name='пояснение')),
            ],
            options={
                'verbose_name': 'статус товара',
                'verbose_name_plural': 'статусы товаров',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('description', models.TextField(blank=True, verbose_name='описание раздела')),
                ('parent', models.ForeignKey(blank=True, help_text='Пусто — раздел верхнего уровня, он попадёт в меню сайта.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='родительский раздел')),
            ],
            options={
                'verbose_name': 'раздел каталога',
                'verbose_name_plural': 'разделы каталога',
                'ordering': ('position', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('name_uk', models.CharField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское название.', max_length=160, verbose_name='название по-украински')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать')),
                ('position', models.PositiveSmallIntegerField(default=100, verbose_name='порядок')),
                ('article', models.CharField(max_length=32, unique=True, verbose_name='артикул')),
                ('summary', models.CharField(blank=True, help_text='Одна-две строки. Видно в карточке товара под названием.', max_length=300, verbose_name='краткое описание')),
                ('summary_uk', models.CharField(blank=True, max_length=300, verbose_name='краткое описание по-украински')),
                ('description', models.TextField(blank=True, help_text='Показывается на странице товара отдельным блоком.', verbose_name='полное описание')),
                ('description_uk', models.TextField(blank=True, help_text='Если не заполнить, на украинской версии сайта покажется русское описание.', verbose_name='полное описание по-украински')),
                ('family', models.CharField(blank=True, db_index=True, help_text='Одинаковое слово у букетов, которые отличаются только размером: на странице появится переключатель. Например «rozy-krasnye». Пусто — вариантов нет.', max_length=64, verbose_name='семейство вариантов')),
                ('composition', models.TextField(blank=True, help_text='Что внутри: «25 роз, эвкалипт, крафт-упаковка».', verbose_name='состав')),
                ('composition_uk', models.TextField(blank=True, verbose_name='состав по-украински')),
                ('stems', models.PositiveIntegerField(default=0, help_text='0 — не показывать. Для растения в горшке не нужно.', verbose_name='цветков в букете')),
                ('height_cm', models.PositiveIntegerField(default=0, help_text='0 — не показывать.', verbose_name='высота, см')),
                ('stock_quantity', models.PositiveIntegerField(db_index=True, default=0, help_text='Сколько букетов можно собрать сегодня.', verbose_name='остаток, штук')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Розничная цена за один букет.', max_digits=9, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Заполните, если хотите показать зачёркнутую цену.', max_digits=9, null=True, verbose_name='старая цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='раздел')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.color', verbose_name='цвет')),
                ('flowers', models.ManyToManyField(blank=True, help_text='Можно выбрать несколько: в сборном букете цветов много.', related_name='products', to='catalog.flower', verbose_name='цветы')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.kind', verbose_name='тип товара')),
                ('occasions', models.ManyToManyField(blank=True, help_text='По каким поводам предлагать этот букет.', related_name='products', to='catalog.occasion', verbose_name='поводы')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.size', verbose_name='размер')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.status', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('position', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='файл')),
                ('alt', models.CharField(blank=True, max_length=160, verbose_name='подпись')),
                ('position', models.PositiveSmallIntegerField(default=100, help_text='Чем меньше число, тем раньше фото. Первое — обложка.', verbose_name='порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
                'ordering': ('position', 'id'),
            },
        ),
    ]
