# Generated by Django 5.2.17 on 2026-09-16 18:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('phone', models.CharField(max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('delivery', models.CharField(choices=[('courier', 'Курьером по городу'), ('pickup', 'Самовывоз из магазина')], default='courier', max_length=16, verbose_name='доставка')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='дата доставки')),
                ('delivery_time', models.CharField(blank=True, choices=[('09-12', '09:00–12:00'), ('12-15', '12:00–15:00'), ('15-18', '15:00–18:00'), ('18-21', '18:00–21:00')], max_length=8, verbose_name='время')),
                ('recipient_name', models.CharField(blank=True, help_text='Если букет — подарок и получает его другой человек.', max_length=120, verbose_name='получатель')),
                ('recipient_phone', models.CharField(blank=True, max_length=40, verbose_name='телефон получателя')),
                ('card_text', models.CharField(blank=True, help_text='Что написать на открытке к букету.', max_length=300, verbose_name='текст открытки')),
                ('payment', models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Переводом на карту')], default='cash', max_length=16, verbose_name='оплата')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий покупателя')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('delivering', 'Доставляется'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=16, verbose_name='статус')),
                ('manager_note', models.TextField(blank=True, verbose_name='заметка флориста')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='всего штук')),
                ('goods_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, verbose_name='товары на сумму')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='доставка')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, verbose_name='итого')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='кабинет покупателя')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('article', models.CharField(max_length=32, verbose_name='артикул')),
                ('product_name', models.CharField(max_length=200, verbose_name='название')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество, штук')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена за штуку')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'строка заказа',
                'verbose_name_plural': 'строки заказа',
                'ordering': ('id',),
            },
        ),
    ]
