# Generated by Django 5.2.17 on 2026-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, max_length=5, verbose_name='язык сайта'),
        ),
    ]
